### ISSUE TITLE
Does not work under python 2.5

### ISSUE THREAD

**Issue by PaoloC68** [MegaMark16/django-cms-themes#4]
When running on python 2.5 throws the following syntax error

```
except Exception as ex:
                  ^
SyntaxError: invalid syntax
```

which can be easily  fixed by replacing the as command with a comma:

so instead:

```
except Exception as ex:
```

use

```
except Exception, ex:
```

and will be fine.

reference http://www.gossamer-threads.com/lists/python/python/785327

**Comment by MegaMark16** [comment]
Sorry for the delay, but I've made the change you suggested.  Thanks!
